Repository TremboGuys/eatly_frontend, pull requests merged in 2025-06, with the labels that each got.

#29 feat-28
  package-lock.json
  package.json
  src/plugins/axios.js
Labels: good first issue

#31 FEAT: Create page of category record #30.
  src/assets/sass/inputs/_inputFile.scss
  src/assets/sass/registerCategory/_registerCategory.scss
  src/components/buttons/ButtonSubmit.vue
  src/components/index.js
  src/components/inputs/InputFile.vue
  src/router/index.js
  src/views/RegisterCategoryView.vue
Labels: enhancement

#35 Dev
  vercel.json
Labels: fix

#37 Dev
  vercel.json
Labels: fix

#38 Add static.json for routes in Render #30
  static.json
  vercel.json
Labels: bug

#39 Dev
  static.json
  vercel.json
Labels: enhancement

#32 Feat 27
  package-lock.json
  package.json
  src/assets/sass/searchPage/_SearchBarContainer.scss
  src/assets/sass/searchPage/_foodCategory.scss
  src/assets/sass/searchPage/_searchBar.scss
  src/assets/sass/searchPage/_searchList.scss
  src/assets/sass/searchPage/_searchPage.scss
  src/components/searchPage/FoodCategory.vue
  src/components/searchPage/SearchBar.vue
  src/components/searchPage/SearchBarContainer.vue
  src/components/searchPage/SearchList.vue
  src/components/searchPage/SearchPageContainer.vue
  src/composables/category.js
  src/plugins/axios.js
  src/services/category.js
  src/services/index.js
  src/stores/toastStore.js
  src/views/SearchView.vue
Labels: enhancement

#40 Feat 30
  src/components/inputs/InputFile.vue
  src/components/inputs/InputsProps.vue
  src/components/searchPage/SearchList.vue
  src/composables/category.js
  src/composables/index.js
  src/plugins/README.md
  src/plugins/axios.js
  src/services/category.js
  src/views/RegisterCategoryView.vue
  src/views/auth/SignInView.vue
  src/views/auth/SignUpView.vue
Labels: enhancement
