Repository TremboGuys/eatly_frontend, pull requests merged in 2025-05, with the labels that each got.

#5 FEAT: Create initial project and dependencies.
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  src/App.vue
  src/assets/README.md
  src/assets/img/README.md
  src/assets/sass/README.md
  src/components/README.md
  src/composables/README.md
  src/layouts/README.md
  src/main.js
  src/plugins/README.md
  src/router/index.js
  src/stores/counter.js
  src/utils/README.md
  src/views/HomeView.vue
  vite.config.js
Labels: enhancement

#11 REFACTOR: Remove the documents folder with its files
  docs/README.md
  docs/ciclo_da_venda.webp
  docs/modelagem_eatly.png
  docs/pdf_modelagem_eatly.pdf
Labels: documentation

#12 feat-4
  src/router/index.js
  src/views/DashboardView.vue
  src/views/auth/SignInView.vue
  src/views/auth/SignUpView.vue
  src/views/restaurant/CreateReviewView.vue
  src/views/restaurant/RestaurantView.vue
  src/views/restaurant/ReviewsView.vue
Labels: good first issue

#17 FEAT: Component Not Found finished #16.
  src/components/notFound/NotFound.vue
Labels: enhancement

#20 REFACTOR: Create DefaultLayout #19
  src/components/index.js
  src/layouts/DefaultLayout.vue
  src/router/index.js
Labels: fix
