Repository TremboGuys/eatly_frontend, pull requests merged in 2025-09, with the labels that each got.

#44 Feat 43
  src/assets/sass/registerCategory/_registerCategory.scss
  src/assets/sass/registerOwner/_registerOwner.scss
  src/composables/index.js
  src/composables/owner.js
  src/router/index.js
  src/services/index.js
  src/services/owner.js
  src/views/RegisterOwnerView.vue
  src/views/RegisterRestaurantView.vue
Labels: enhancement

#46 Feat 45
  src/assets/sass/buttons/_sendButton.scss
  src/assets/sass/registerOwner/_customSelect.scss
  src/assets/sass/registerOwner/_registerOwner.scss
  src/assets/sass/registerRestaurant/_customSelect.scss
  src/assets/sass/registerRestaurant/_registerRestaurant.scss
  src/components/index.js
  src/components/inputs/CustomSelect.vue
  src/composables/owner.js
  src/composables/restaurant.js
  src/metaDatas/categories.js
  src/router/index.js
  src/services/owner.js
  src/services/restaurant.js
  src/views/RegisterRestaurantView.vue
Labels: enhancement

#65 FIX: Fix in URL.
  src/plugins/axios.js
Labels: fix

#69 FIX: Fix axios #56
  src/plugins/axios.js
Labels: enhancement

#73 FIX: Fix URL for refresh access token #56
  src/plugins/axios.js
  src/router/index.js
  src/services/auth/auth.js
  src/services/category.js
  src/services/owner.js
  src/services/restaurant.js
  src/stores/auth/auth.js
Labels: enhancement

#75 REFACTOR: Organize and clean up navigation bar styles
  src/assets/sass/navigationBar/_navIcons.scss
  src/assets/sass/navigationBar/_navigationBar.scss
Labels: enhancement

#77 Feat 61
  package-lock.json
  package.json
  src/assets/img/banner.png
  src/assets/sass/restaurantPage/_restaurantPage.scss
  src/assets/sass/restaurantPage/banner/_assessmentStar.scss
  src/assets/sass/restaurantPage/banner/_bannerComp.scss
  src/assets/sass/restaurantPage/banner/_basicInfo.scss
  src/assets/sass/restaurantPage/banner/_deliveryComp.scss
  src/assets/sass/restaurantPage/banner/_nameComp.scss
  src/assets/sass/restaurantPage/banner/_priceTime.scss
  src/assets/sass/restaurantPage/banner/_restaurantImage.scss
  src/assets/sass/restaurantPage/menu/_itemsMenu.scss
  src/assets/sass/restaurantPage/options/_optionsScroll.scss
  src/components/index.js
  src/components/restaurantPage/banner/AssessmentStar.vue
  src/components/restaurantPage/banner/BannerComp.vue
  src/components/restaurantPage/banner/BasicInfo.vue
  src/components/restaurantPage/banner/DeliveryComp.vue
  src/components/restaurantPage/banner/NameComp.vue
  src/components/restaurantPage/banner/PriceTime.vue
  src/components/restaurantPage/banner/RestaurantImage.vue
  src/components/restaurantPage/menu/ItemMenu.vue
  src/components/restaurantPage/menu/ItemsMenu.vue
  src/components/restaurantPage/options/OptionsScroll.vue
  src/main.js
  src/metaDatas/menuData.js
  src/router/index.js
  src/views/restaurant/RestaurantView.vue
Labels: enhancement

#84 Feat 79
  src/assets/img/productPage/imageProduct.jpg
  src/assets/img/productPage/imageProduct2.jpg
  src/assets/img/productPage/imageProduct3.jpg
  src/assets/sass/productPage/_descriptionProduct.scss
  src/assets/sass/productPage/_imageProduct.scss
  src/assets/sass/productPage/_productCart.scss
  src/assets/sass/productPage/_ratingProduct.scss
  src/assets/sass/productPage/_titleProduct.scss
  src/assets/sass/restaurantPage/banner/_basicInfo.scss
  src/components/index.js
  src/components/productPage/DescriptionProduct.vue
  src/components/productPage/ImageProduct.vue
  src/components/productPage/ProductCart.vue
  src/components/productPage/RatingProduct.vue
  src/components/productPage/TitleProduct.vue
  src/components/restaurantPage/menu/ItemsMenu.vue
  src/layouts/DefaultLayout.vue
  src/router/index.js
  src/views/restaurant/ProductView.vue
Labels: enhancement, fix

#87 feat-53
  package-lock.json
  package.json
  src/assets/banners/1600w-ETpMxiC9aXg.webp
  src/assets/banners/1600w-axxWJ7FLGWE.webp
  src/assets/banners/1600w-fklzM_Het_M.webp
  src/assets/banners/1600w-n7WGqTlRrIw.webp
  src/assets/banners/1600w-xPGAjV9zPS0.webp
  src/assets/img/Group.png
  src/assets/img/burger.png
  src/assets/img/carrinho.png
  src/assets/img/navigationBar/Profile.png
  src/assets/img/pizza.png
  src/assets/img/refrigerantes.png
  src/assets/img/undraw_breakfast_rgx5 1.png
  src/assets/sass/home/_bestSellersContainer.scss
  src/assets/sass/home/_bottomAds.scss
  src/assets/sass/home/_categories.scss
  src/assets/sass/home/_categoryBox.scss
  src/assets/sass/home/_headerDesktop.scss
  src/assets/sass/home/_headerList.scss
  src/assets/sass/home/_homeCaroulsel.scss
  src/assets/sass/home/_homeCarousel.scss
  src/assets/sass/home/_homeContainer.scss
  src/assets/sass/home/_listItem.scss
  src/assets/sass/home/_logoArea.scss
  src/assets/sass/home/_profileIcon.scss
  src/assets/sass/navigationBar/_navigationBar.scss
  src/components/home/AdsImage.vue
  src/components/home/BottomAds.vue
  src/components/home/CategoryCarousel.vue
  src/components/home/HomeContainer.vue
  src/components/home/LogoArea.vue
  src/components/home/SeenPreviously.vue
  src/components/home/bestsellers/BestSellersContainer.vue
  src/components/home/bestsellers/BestSellersList.vue
  src/components/home/bestsellers/HeaderList.vue
  src/components/home/bestsellers/ListItem.vue
  src/components/home/carousel/HomeCaroulselContainer.vue
  src/components/home/categories/CategoryBox.vue
  src/components/home/categories/HomeCategories.vue
  src/components/home/desktop/HeaderDesktop.vue
  src/components/home/desktop/ProfileIcon.vue
  src/components/home/desktop/SearchButton.vue
  src/components/inputs/InputsProps.vue
  src/composables/auth/client.js
  src/router/index.js
  src/services/auth/auth.js
  src/services/auth/client.js
  src/services/index.js
  src/stores/auth/client.js
  src/views/HomeView.vue
  src/views/auth/client/SignInClientView.vue
Labels: enhancement

#89 feat-88
  src/assets/sass/home/_bestSellersContainer.scss
  src/assets/sass/home/_listItem.scss
  src/components/home/HomeContainer.vue
  src/components/home/SeenPreviously.vue
  src/components/home/bestsellers/BestSellersContainer.vue
  src/components/home/bestsellers/BestSellersList.vue
  src/components/home/bestsellers/HeaderList.vue
  src/components/home/bestsellers/ListItem.vue
  src/components/index.js
  src/components/inputs/InputsProps.vue
  src/components/productPage/ImageProduct.vue
  src/components/restaurantPage/banner/AssessmentStar.vue
  src/components/restaurantPage/banner/BannerComp.vue
  src/components/restaurantPage/banner/BasicInfo.vue
  src/components/restaurantPage/banner/DeliveryComp.vue
  src/components/restaurantPage/banner/NameComp.vue
  src/components/restaurantPage/banner/RestaurantImage.vue
  src/components/restaurantPage/menu/ItemsMenu.vue
  src/components/restaurantPage/options/OptionsScroll.vue
  src/composables/index.js
  src/layouts/DefaultLayout.vue
  src/router/index.js
  src/services/auth/user.js
  src/services/index.js
  src/services/restaurant.js
  src/stores/auth/user.js
  src/stores/index.js
  src/stores/restaurant.js
  src/views/HomeView.vue
  src/views/RegisterRestaurantView.vue
  src/views/auth/client/SignInClientView.vue
  src/views/restaurant/RestaurantView.vue
Labels: enhancement

#91 FIX: Fix baseURL #88
  src/plugins/axios.js
Labels: enhancement

#95 FIX: Fix in bugs and adjust of styles after deploy.
  src/assets/sass/home/_listItem.scss
  src/assets/sass/restaurantPage/menu/_itemsMenu.scss
  src/components/productPage/ProductCart.vue
  src/components/productPage/TitleProduct.vue
  src/components/restaurantPage/menu/ItemsMenu.vue
  src/stores/cartStore.js
  src/views/restaurant/RestaurantView.vue
Labels: fix

#98 dev
  src/components/cart/CartItem.vue
  src/components/home/SeenPreviously.vue
  src/components/home/bestsellers/BestSellersList.vue
  src/composables/auth/client.js
  src/composables/product.js
  src/services/auth/auth.js
  src/services/auth/user.js
  src/services/restaurant.js
  src/stores/auth/client.js
  src/stores/auth/user.js
  src/stores/cartStore.js
  src/stores/restaurant.js
  src/views/restaurant/RestaurantView.vue
Labels: bug
